name: Custom Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild Armbian and Kernel
        uses: ophub/amlogic-s9xxx-armbian@Armbian_trixie_save_2025.10

      - name: Metrics embed
        uses: lowlighter/metrics@v3.34

      - name: Gosec Security Checker
        uses: securego/gosec@v2.22.10
        with:
          args: "VASCO"
